#!/bin/bash

set -euo pipefail

connect_tailscale() {
    TS_USERNAME=$(echo "${GITPOD_GIT_USER_NAME}" | tr " " '-')
    TS_HOSTNAME="${TS_USERNAME}-${GITPOD_WORKSPACE_ID}"
    sudo -E tailscale up --accept-dns --accept-routes --hostname="$TS_HOSTNAME"
}

if /usr/bin/tmux has-session -t tailscaled 2>/dev/null; then
    echo "Tailscaled Running"
    connect_tailscale
else
    echo "Tailscaled Stopped, Starting"
    tmux new-session -d -s tailscaled 'sudo /usr/sbin/tailscaled --state=mem:'
    connect_tailscale
fi
